### PR TITLE
cleanup: PEP8 fixes and some cleanup

### PR DESCRIPTION
**Pull request by tasdikrahman**
Added documentation to places and made some files PEP8 conformant.

### CODE REVIEW

**Comment by mguida22** [comment]
Hey thanks for the PR! Have you tested it with your changes?

**Comment by tasdikrahman** [comment]
@mguida22 works on Ubuntu 14.10 :+1: 

The directory functions are cross platform, so should work on both MAC and windows

**Comment by mguida22** [comment]
@prodicus let me know if you want to work on this project. We want to see it improve but don't have too much time ourselves to put in work now. I can give you some guidance and help if you do want to contribute more

**Comment by tasdikrahman** [comment]
@mguida22 Would be more than happy to assist in whatever way I can :smile:

**Comment by mguida22** [comment]
@prodicus if you want, take a look at #22. That's a good place to start, I'll add some more information on that issue. If you have any question on it feel free to let me know

**Pull request merged**
