### PR TITLE
Auto documentation 

### PR DESCRIPTION
**Pull request by nicolele**
Automatic documentation generated using Sphinx. 
- Creates PDF
- Creates HTML

### CODE REVIEW

**Comment by mguida22** [comment]
@nicolele can you add the `backend/_build/`folder to the `.gitignore`. We don't want to commit all of that stuff.

**Comment by nicolele** [comment]
@mguida22 I deleted the directory with all the JS libraries but I left some things since the actual auto documentation is stored in _build. I can try to remove more though if it seems like there's too much still.

**Comment by mguida22** [comment]
maybe @719Ben or @kyliedale have some ideas. Usually you don't commit build files, just instructions to make them locally. I'd just only add the pdf, or nothing at all but its up to you

**Comment by biw** [comment]
We should maybe leave them just until we get the project graded. Once it's graded I think we should add it to the gitignore but I'm afraid that they might think we didn't have docs if we do ignore it.

**Comment by mguida22** [comment]
:+1: alright lets leave it

**Comment by biw** [comment]
:shipit:

**Comment by mguida22** [comment]
image

**Comment by nicolele** [comment]
i could get rid of the extra files in the latex directory also and just keep the pdf but @719Ben might be right that they'll think we didn't have it auto generated or whatever

**Comment by mguida22** [comment]
'tis true

**Comment by biw** [comment]
I say we keep everything right now. We can clean stuff up once this class assignment is over and we start making this a real public project. Does that sound good @nicolele and @mguida22?

**Pull request merged**
